# Generated by Django 5.2.16 on 2026-07-10 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntoGraficas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo_original', models.CharField(blank=True, max_length=255)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conjunto de gráficas',
                'verbose_name_plural': 'Conjuntos de gráficas',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='RegistroEnergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('id_cliente', models.CharField(max_length=50)),
                ('tipo_energia', models.CharField(choices=[('Activa', 'Activa'), ('Reactiva', 'Reactiva'), ('Capacitiva', 'Capacitiva'), ('Penalizada', 'Penalizada'), ('Factor', 'Factor')], max_length=20)),
                ('horas', models.JSONField(help_text='Lista de 24 valores, Hora 1 a Hora 24')),
                ('total', models.FloatField(blank=True, null=True)),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='graficas.conjuntograficas')),
            ],
            options={
                'verbose_name': 'Registro de energía',
                'verbose_name_plural': 'Registros de energía',
                'ordering': ['fecha', 'tipo_energia'],
                'indexes': [models.Index(fields=['conjunto', 'tipo_energia'], name='graficas_re_conjunt_785472_idx'), models.Index(fields=['conjunto', 'fecha'], name='graficas_re_conjunt_b70749_idx')],
            },
        ),
    ]
